import { Nunito } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast"

const nunito = Nunito({
  subsets: ["cyrillic"],
  variable: "--font-nunito",
  weight: ["400", "500", "600", "700", "800", "900"],
});

// export const metadata: Metadata = {
//   title: "My Pizza | Главная",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={nunito.variable} lang="en">
        <head>
            <link data-rh="true" rel="icon" href="/logo.png" />
        </head>
      <body className={nunito.variable}>{children}
        <Toaster />
      </body>
    </html>
  );
}
